apiVersion: v1
kind: Service
metadata:
  name: explorer-rest-api
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: explorer-rest-api
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: rest
status:
  loadBalancer: {}
