apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum.fullname" . }}-solidity-browser
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: solidity-browser
spec:
  type: LoadBalancer
  selector:
    app: solidity
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ethereum.fullname" . }}-solidity-browser
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: solidity-browser 
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "ethereum.fullname" . }}-solidity-browser 
      labels:
        app: {{ template "ethereum.name" . }}
        chart: {{ template "ethereum.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: solidity-browser
    spec:
      containers:
      - name: solidity
        image: kairen/solidity
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
cpu: "0.5"
