apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: explorer-ui
  name: explorer-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: REACT_APP_EXPLORER
          value: http://blockapi.dappbox.io
        image: blkio10/explorer-ui-free:1.0.0
        name: blk-explorer-ui-free
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
